### ISSUE TITLE
Cannot use generate command when contract has a const parameter

### ISSUE THREAD

**Issue by nbusser** [completium/completium-cli#40]
Hello Completium team.

## Problem description

I have a problem when trying to use
- `completium-cli generate michelson minimal.arl`
-  `completium-cli generate javascript minimal.arl`

The problem occurs whenever using a `const` parameter in the contract definition.  
I get the following error when compiling: `Cannot read property 'val' of undefined`.

## Minimal example

```
archetype minimal(const val: nat)
entry mock() {}
```

## Working example

To fix the issue, removing the `const` is enough:
```
archetype minimal(val: nat)
entry mock() {}
```

As further as I understood, `const` keyword is just a protection against miss-writing of the wrong variable. It should have no counterpart in Michelson.

## Found workaround

Using directly archetype compiler works:

`archetype minimal.arl`

It generates the following Michelson code:
```
# Unit
{
  storage unit;
  parameter (unit %mock);
  code { UNPAIR;
         DROP;
         NIL operation;
         PAIR };
}
```

**Comment by guillaumeduhamel** [comment]
Hi @nbusser,
thank you for this detailed issue,
I think it works with the latest version of completium-cli/archetype:
```
$ completium-cli version
0.4.9
$ completium-cli archetype version
1.3.3
$ cat minimal.arl 
archetype minimal(const val: nat)

variable n : nat = 0

entry mock() {
  n := val
}
$ completium-cli generate michelson minimal.arl --parameters '{"val" : 1}'
# 0
{
  storage nat;
  parameter (unit %mock);
  code { UNPAIR;
         DROP;
         PUSH nat 1;
         SWAP;
         DROP;
         NIL operation;
         PAIR };
}
```

Please, let me know if it works on your side too

**Comment by nbusser** [comment]
Hello @guillaumeduhamel, thank you for your quick answer.

It actually works with my version

```
completium-cli version
0.4.8

completium-cli archetype version
1.3.2
```

The problem was I didn't specified the contract's parameters using `--parameters` option.

You should consider to add it somewhere in the [documentation of Completium](https://completium.com/docs/cli/contract#generate-javascript). I think it lacks this information.
